import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Random from "@/random_button";


export default function Home() {

  const classFilters = {
    1: { name: 'Magician', image: 'Circle.png' },
    2: { name: 'Thief', image: 'Circle.png' },
    4: { name: 'Warrior', image: 'Circle.png' },
    8: { name: 'Bowman', image: 'Circle.png' },
    16: { name: 'Pirate', image: 'Circle.png' },
    32: { name: 'None', image: 'Circle.png' },
  }
  
  const [input, setInput] = useState('');

  const selectedItem = Object.keys(classFilters).filter(item => (input & item) > 0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.backgroundImage}`}>
      
        <input
          id="input"
          type="text"
          placeholder="bitmask decimal value"
          value={input}
          onChange={event => setInput(event.target.value)}
        />
        <Random setInput={setInput}/>
        {input && (
          <table>
            <tbody>
              {
                selectedItem.map(item => (
                  <tr key= {item} style={{ backgroundColor: 'null' }}>
                    <td>
                      <img
                        src={classFilters[item].image}
                      />
                    </td>
                    <td>{item}</td>
                    <td>{classFilters[item].name}</td>
                  </tr>
                ))
              }
            </tbody>
          </table>
        )}
      </main>
    </>
  );
}


